import React, { useRef } from 'react';
import { X, Download, TrendingUp, TrendingDown, AlertTriangle, CheckCircle, PieChart, DollarSign } from 'lucide-react';
import { PieChart as RechartsPie, Pie, Cell, ResponsiveContainer, Legend, Tooltip } from 'recharts';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

const COLORS = ['#8b5cf6', '#ec4899', '#f59e0b', '#10b981', '#3b82f6', '#ef4444', '#14b8a6', '#f97316'];

const AIReportModal = ({ isOpen, onClose, reportData, expenses, budget }) => {
    const reportRef = useRef();

    if (!isOpen) return null;

    const totalSpent = expenses.reduce((sum, e) => sum + e.amount, 0);
    const remaining = budget - totalSpent;
    const isOverBudget = remaining < 0;

    // Category breakdown
    const categoryData = {};
    expenses.forEach(exp => {
        categoryData[exp.category] = (categoryData[exp.category] || 0) + exp.amount;
    });

    const chartData = Object.entries(categoryData).map(([name, value]) => ({ name, value }));
    const sortedCategories = Object.entries(categoryData).sort((a, b) => b[1] - a[1]);
    const topCategory = sortedCategories[0];

    // AI Analysis
    const aiInsights = generateAIInsights(expenses, budget, totalSpent, categoryData);

    const handleDownloadPDF = () => {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.width;
        
        // Header
        doc.setFillColor(139, 92, 246);
        doc.rect(0, 0, pageWidth, 40, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(24);
        doc.setFont(undefined, 'bold');
        doc.text('Monthly Financial Report', pageWidth / 2, 25, { align: 'center' });
        
        // Date
        doc.setFontSize(10);
        doc.setFont(undefined, 'normal');
        doc.text(`Generated on: ${new Date().toLocaleDateString()}`, pageWidth / 2, 35, { align: 'center' });
        
        let yPos = 55;
        
        // Summary Section
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(16);
        doc.setFont(undefined, 'bold');
        doc.text('Financial Summary', 14, yPos);
        yPos += 10;
        
        doc.autoTable({
            startY: yPos,
            head: [['Metric', 'Amount']],
            body: [
                ['Monthly Budget', `₹${budget.toFixed(2)}`],
                ['Total Expenses', `₹${totalSpent.toFixed(2)}`],
                ['Remaining Balance', `₹${remaining.toFixed(2)}`],
                ['Status', isOverBudget ? 'Over Budget ⚠️' : 'Within Budget ✓']
            ],
            theme: 'striped',
            headStyles: { fillColor: [139, 92, 246] }
        });
        
        yPos = doc.lastAutoTable.finalY + 15;
        
        // Category Breakdown
        doc.setFontSize(16);
        doc.setFont(undefined, 'bold');
        doc.text('Category Breakdown', 14, yPos);
        yPos += 10;
        
        const categoryRows = sortedCategories.map(([cat, amount]) => [
            cat,
            `₹${amount.toFixed(2)}`,
            `${((amount / totalSpent) * 100).toFixed(1)}%`
        ]);
        
        doc.autoTable({
            startY: yPos,
            head: [['Category', 'Amount', 'Percentage']],
            body: categoryRows,
            theme: 'striped',
            headStyles: { fillColor: [139, 92, 246] }
        });
        
        yPos = doc.lastAutoTable.finalY + 15;
        
        // AI Insights
        if (yPos > 250) {
            doc.addPage();
            yPos = 20;
        }
        
        doc.setFontSize(16);
        doc.setFont(undefined, 'bold');
        doc.text('AI Financial Insights', 14, yPos);
        yPos += 10;
        
        doc.setFontSize(11);
        doc.setFont(undefined, 'normal');
        const splitText = doc.splitTextToSize(aiInsights.summary, pageWidth - 28);
        doc.text(splitText, 14, yPos);
        yPos += splitText.length * 7 + 10;
        
        // Recommendations
        doc.setFontSize(14);
        doc.setFont(undefined, 'bold');
        doc.text('Recommendations', 14, yPos);
        yPos += 8;
        
        doc.setFontSize(10);
        doc.setFont(undefined, 'normal');
        aiInsights.recommendations.forEach((rec, idx) => {
            const recText = doc.splitTextToSize(`${idx + 1}. ${rec}`, pageWidth - 28);
            doc.text(recText, 14, yPos);
            yPos += recText.length * 6 + 3;
        });
        
        // Footer
        const totalPages = doc.internal.pages.length - 1;
        for (let i = 1; i <= totalPages; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(128, 128, 128);
            doc.text(`Page ${i} of ${totalPages}`, pageWidth / 2, doc.internal.pageSize.height - 10, { align: 'center' });
            doc.text('Generated by Zentrack AI Assistant', pageWidth / 2, doc.internal.pageSize.height - 5, { align: 'center' });
        }
        
        doc.save(`Financial_Report_${new Date().toISOString().split('T')[0]}.pdf`);
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50 backdrop-blur-sm animate-fadeIn p-4">
            <div className="bg-white rounded-2xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-hidden animate-slideUp">
                {/* Header */}
                <div className="bg-gradient-to-r from-purple-600 to-pink-600 p-6 text-white">
                    <div className="flex justify-between items-center">
                        <div>
                            <h2 className="text-2xl font-bold flex items-center gap-2">
                                <TrendingUp size={28} />
                                AI Financial Report
                            </h2>
                            <p className="text-purple-100 text-sm mt-1">Generated on {new Date().toLocaleDateString()}</p>
                        </div>
                        <button onClick={onClose} className="hover:bg-white/20 p-2 rounded-full transition">
                            <X size={24} />
                        </button>
                    </div>
                </div>

                {/* Content */}
                <div ref={reportRef} className="overflow-y-auto max-h-[calc(90vh-180px)] p-6 space-y-6">
                    
                    {/* Summary Cards */}
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                        <div className="bg-gradient-to-br from-purple-50 to-purple-100 rounded-xl p-4 border border-purple-200">
                            <div className="flex items-center gap-2 text-purple-700 mb-2">
                                <DollarSign size={20} />
                                <p className="text-sm font-medium">Monthly Budget</p>
                            </div>
                            <p className="text-2xl font-bold text-purple-900">₹{budget.toFixed(2)}</p>
                        </div>
                        
                        <div className="bg-gradient-to-br from-pink-50 to-pink-100 rounded-xl p-4 border border-pink-200">
                            <div className="flex items-center gap-2 text-pink-700 mb-2">
                                <TrendingDown size={20} />
                                <p className="text-sm font-medium">Total Expenses</p>
                            </div>
                            <p className="text-2xl font-bold text-pink-900">₹{totalSpent.toFixed(2)}</p>
                        </div>
                        
                        <div className={`bg-gradient-to-br rounded-xl p-4 border ${isOverBudget ? 'from-red-50 to-red-100 border-red-200' : 'from-green-50 to-green-100 border-green-200'}`}>
                            <div className={`flex items-center gap-2 mb-2 ${isOverBudget ? 'text-red-700' : 'text-green-700'}`}>
                                {isOverBudget ? <AlertTriangle size={20} /> : <CheckCircle size={20} />}
                                <p className="text-sm font-medium">Remaining</p>
                            </div>
                            <p className={`text-2xl font-bold ${isOverBudget ? 'text-red-900' : 'text-green-900'}`}>
                                ₹{remaining.toFixed(2)}
                            </p>
                        </div>
                    </div>

                    {/* Category Breakdown with Chart */}
                    <div className="bg-slate-50 rounded-xl p-6 border border-slate-200">
                        <h3 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
                            <PieChart size={20} className="text-purple-600" />
                            Category Breakdown
                        </h3>
                        
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                            {/* Chart */}
                            <div className="flex items-center justify-center">
                                <ResponsiveContainer width="100%" height={200}>
                                    <RechartsPie>
                                        <Pie
                                            data={chartData}
                                            cx="50%"
                                            cy="50%"
                                            innerRadius={50}
                                            outerRadius={80}
                                            dataKey="value"
                                            label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                                        >
                                            {chartData.map((entry, index) => (
                                                <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                                            ))}
                                        </Pie>
                                        <Tooltip />
                                    </RechartsPie>
                                </ResponsiveContainer>
                            </div>
                            
                            {/* Category List */}
                            <div className="space-y-3">
                                {sortedCategories.map(([category, amount], idx) => (
                                    <div key={category} className="flex justify-between items-center">
                                        <div className="flex items-center gap-2">
                                            <div className="w-3 h-3 rounded-full" style={{ backgroundColor: COLORS[idx % COLORS.length] }}></div>
                                            <span className="font-medium text-slate-700">{category}</span>
                                        </div>
                                        <div className="text-right">
                                            <p className="font-bold text-slate-800">₹{amount.toFixed(2)}</p>
                                            <p className="text-xs text-slate-500">{((amount / totalSpent) * 100).toFixed(1)}%</p>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>

                    {/* AI Insights */}
                    <div className="bg-gradient-to-br from-purple-50 to-pink-50 rounded-xl p-6 border border-purple-200">
                        <h3 className="text-lg font-bold text-slate-800 mb-3 flex items-center gap-2">
                            <TrendingUp size={20} className="text-purple-600" />
                            AI Financial Analysis
                        </h3>
                        <p className="text-slate-700 leading-relaxed mb-4">{aiInsights.summary}</p>
                        
                        {/* Key Findings */}
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-4">
                            {aiInsights.keyFindings.map((finding, idx) => (
                                <div key={idx} className={`p-3 rounded-lg border ${finding.type === 'warning' ? 'bg-red-50 border-red-200' : finding.type === 'success' ? 'bg-green-50 border-green-200' : 'bg-blue-50 border-blue-200'}`}>
                                    <p className={`text-sm font-medium ${finding.type === 'warning' ? 'text-red-800' : finding.type === 'success' ? 'text-green-800' : 'text-blue-800'}`}>
                                        {finding.icon} {finding.text}
                                    </p>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Recommendations */}
                    <div className="bg-white rounded-xl p-6 border border-slate-200">
                        <h3 className="text-lg font-bold text-slate-800 mb-4">💡 Smart Recommendations</h3>
                        <div className="space-y-3">
                            {aiInsights.recommendations.map((rec, idx) => (
                                <div key={idx} className="flex gap-3 p-3 bg-purple-50 rounded-lg border border-purple-100 hover:bg-purple-100 transition">
                                    <span className="flex-shrink-0 w-6 h-6 bg-purple-600 text-white rounded-full flex items-center justify-center text-sm font-bold">
                                        {idx + 1}
                                    </span>
                                    <p className="text-slate-700">{rec}</p>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Warnings */}
                    {aiInsights.warnings.length > 0 && (
                        <div className="bg-red-50 rounded-xl p-6 border border-red-200">
                            <h3 className="text-lg font-bold text-red-800 mb-4 flex items-center gap-2">
                                <AlertTriangle size={20} />
                                Alerts & Warnings
                            </h3>
                            <div className="space-y-2">
                                {aiInsights.warnings.map((warning, idx) => (
                                    <div key={idx} className="flex items-start gap-2">
                                        <span className="text-red-600 mt-1">⚠️</span>
                                        <p className="text-red-800">{warning}</p>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}
                </div>

                {/* Footer */}
                <div className="bg-slate-50 p-4 border-t border-slate-200 flex justify-between items-center">
                    <p className="text-sm text-slate-600">Powered by Zentrack AI Assistant</p>
                    <div className="flex gap-3">
                        <button onClick={onClose} className="px-4 py-2 bg-slate-200 text-slate-700 rounded-lg hover:bg-slate-300 font-medium transition">
                            Close
                        </button>
                        <button onClick={handleDownloadPDF} className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 font-medium flex items-center gap-2 transition">
                            <Download size={18} />
                            Download PDF
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

// AI Analysis Logic
const generateAIInsights = (expenses, budget, totalSpent, categoryData) => {
    const remaining = budget - totalSpent;
    const isOverBudget = remaining < 0;
    const sortedCategories = Object.entries(categoryData).sort((a, b) => b[1] - a[1]);
    const topCategory = sortedCategories[0];
    const budgetUsagePercent = ((totalSpent / budget) * 100).toFixed(1);

    // Summary
    let summary = '';
    if (isOverBudget) {
        summary = `You've exceeded your monthly budget by ₹${Math.abs(remaining).toFixed(2)} (${budgetUsagePercent}% of budget used). Your highest spending category is ${topCategory[0]} at ₹${topCategory[1].toFixed(2)}, which accounts for ${((topCategory[1] / totalSpent) * 100).toFixed(1)}% of your total expenses. Immediate action is recommended to bring spending under control.`;
    } else if (budgetUsagePercent > 80) {
        summary = `You're approaching your budget limit with ${budgetUsagePercent}% utilized (₹${remaining.toFixed(2)} remaining). ${topCategory[0]} is your largest expense category at ₹${topCategory[1].toFixed(2)}. Consider reducing discretionary spending to stay within budget for the rest of the month.`;
    } else {
        summary = `Great job! You're managing your budget well with ${budgetUsagePercent}% utilized and ₹${remaining.toFixed(2)} remaining. Your primary spending is in ${topCategory[0]} (₹${topCategory[1].toFixed(2)}). Continue monitoring your expenses to maintain this healthy financial position.`;
    }

    // Key Findings
    const keyFindings = [];
    if (isOverBudget) {
        keyFindings.push({ type: 'warning', icon: '⚠️', text: `Over budget by ₹${Math.abs(remaining).toFixed(2)}` });
    } else {
        keyFindings.push({ type: 'success', icon: '✓', text: `Within budget: ₹${remaining.toFixed(2)} remaining` });
    }
    keyFindings.push({ type: 'info', icon: '📊', text: `Top category: ${topCategory[0]} (${((topCategory[1] / totalSpent) * 100).toFixed(1)}%)` });
    keyFindings.push({ type: 'info', icon: '💳', text: `${expenses.length} transactions this month` });
    keyFindings.push({ type: 'info', icon: '📈', text: `Avg expense: ₹${(totalSpent / expenses.length).toFixed(2)}` });

    // Recommendations
    const recommendations = [];
    if (isOverBudget) {
        recommendations.push(`Reduce ${topCategory[0]} spending by at least 20% to get back on track`);
        recommendations.push('Review and eliminate unnecessary subscriptions or recurring expenses');
        recommendations.push('Set daily spending limits and track expenses in real-time');
    } else if (budgetUsagePercent > 80) {
        recommendations.push(`Limit ${topCategory[0]} expenses for the remainder of the month`);
        recommendations.push('Postpone non-essential purchases until next month');
        recommendations.push('Consider meal planning to reduce food-related expenses');
    } else {
        recommendations.push('Allocate surplus funds to savings or emergency fund');
        recommendations.push(`Continue monitoring ${topCategory[0]} category to prevent overspending`);
        recommendations.push('Set aside 10-15% of remaining budget as a safety buffer');
    }

    // Add category-specific recommendations
    if (categoryData['Food'] > budget * 0.3) {
        recommendations.push('Food expenses are high - try meal prepping and cooking at home more often');
    }
    if (categoryData['Entertainment'] > budget * 0.15) {
        recommendations.push('Consider free or low-cost entertainment alternatives');
    }
    if (categoryData['Shopping'] > budget * 0.2) {
        recommendations.push('Implement a 24-hour rule before making non-essential purchases');
    }

    // Warnings
    const warnings = [];
    if (isOverBudget) {
        warnings.push('Budget exceeded! Immediate spending reduction required.');
    }
    if (budgetUsagePercent > 90) {
        warnings.push('Critical: Less than 10% of budget remaining.');
    }
    sortedCategories.forEach(([cat, amount]) => {
        if (amount > budget * 0.4) {
            warnings.push(`${cat} spending (₹${amount.toFixed(2)}) exceeds 40% of total budget.`);
        }
    });

    return {
        summary,
        keyFindings,
        recommendations: recommendations.slice(0, 5),
        warnings
    };
};

export default AIReportModal;
